POST http://localhost:3333/usuarios
Content-type: application/json

{
    "nome": "Augusto Campos",
    "email": "augusto.campos@example.com",
    "senha": "etanos"
}

###

GET http://localhost:3333/usuarios

###

PUT http://localhost:3333/usuarios/5c55c134-a1dc-46ee-9ed5-53b60b930196
Content-type: application/json

{
    "nome": "João Silva Alterado",
    "email": "joao.silva.alterado@example.com",
    "senha": "novaSenha123"
}

###

DELETE http://localhost:3333/usuarios/5c55c134-a1dc-46ee-9ed5-53b60b930196
