POST http://nodeapi-zyiv.onrender.com/usuarios
Content-type: application/json

{
    "nome": "João Souza",
    "email": "joao.souza@example.com",
    "senha": "sen123ha"
}

###

GET http://nodeapi-zyiv.onrender.com/usuarios

###

GET http://nodeapi-zyiv.onrender.com/usuarios?search=souza

###

PUT http://nodeapi-zyiv.onrender.com/usuarios/5c55c134-a1dc-46ee-9ed5-53b60b930196
Content-type: application/json

{
    "nome": "João Silva Alterado",
    "email": "joao.silva.alterado@example.com",
    "senha": "novaSenha123"
}

###

DELETE http://nodeapi-zyiv.onrender.com/usuarios/5c55c134-a1dc-46ee-9ed5-53b60b930196
